name: Deploy Node Backend to EC2

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            echo "Connected to EC2"

            cd /home/ubuntu

            # Clone repo if not exists
            if [ ! -d "./-KUREMEDI-LUCENT-Project/.git" ]; then
              git clone https://github.com/ankurkushwaha809/-KUREMEDI-LUCENT-Project.git ./-KUREMEDI-LUCENT-Project
            fi

            cd -- "-KUREMEDI-LUCENT-Project/backend"

            echo "Pull latest code"
            git pull origin main

            echo "Install dependencies"
            npm install

            echo "Stop old processes"
            pm2 delete all || true

            echo "Start backend"
            pm2 start index.js --name backend

            pm2 save

            echo "Restart nginx"
            sudo systemctl restart nginx

            echo "Deployment successful 🚀"
